const D=window.HEALTH_DATA, $=s=>document.querySelector(s), app=$('#app');
const K={bank:'hss_admin_bank_v2',session:'hss_session_v1',tasks:'hss_tasks_v1',adminPass:'hss_admin_pass_v1'};
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let bank=get(K.bank,D.questions), session=get(K.session,null), route='home', explore=null;
const intake=[
 ['你的年齡大約是？',['18–39 歲','40–64 歲','65 歲以上'],'age'],
 ['你平常的飲食型態比較接近？',['大多數餐都外食','外食與自己準備各半','多數餐自己準備'],'eatingOut'],
 ['你喝含糖飲料的頻率？',['幾乎每天','每週偶爾喝','很少喝'],'sugar'],
 ['你一天大約會坐多久？',['超過 8 小時','約 4–8 小時','少於 4 小時'],'sitting'],
 ['你的運動頻率？',['幾乎沒有規律運動','每週約 1–2 次','每週 3 次以上'],'exercise'],
 ['你最近的睡眠狀況？',['經常睡不好或睡眠不足','偶爾不好','大多穩定'],'sleep'],
 ['你每天使用手機、平板、電腦的時間？',['超過 8 小時','4–8 小時','少於 4 小時'],'digital'],
 ['目前最想改善的健康方向是？',['飲食與代謝','體力與肌力','慢性病預防','睡眠與壓力','數位健康'],'goal']
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};
const shell=(body,back=false)=>`<main class="shell"><header class="topbar">${back?'<button class="home-link" data-act="home">← 回首頁</button>':'<div class="brand">🌿 HSS V1.0</div>'}<button class="icon-btn" data-act="admin" aria-label="管理員設定">⚙️</button></header>${body}<footer class="disclaimer">💡 ${esc(D.sharedDisclaimer)}</footer></main><dialog id="adminDialog"></dialog>`;
function render(){
 if(route==='home') home(); else if(route==='intake') intakePage(); else if(route==='quiz') quizPage(); else if(route==='result') resultPage(); else if(route==='topics') topicsPage(); else if(route==='explore') explorePage();
 bind();
}
function home(){const resume=session&&session.mode==='personal'&&session.index<(session.questionIds?.length||0);app.innerHTML=shell(`<section class="hero"><div class="eyebrow">HEALTH SCENARIO SIMULATOR</div><h1>健康情境<br>模擬器</h1><div class="subtitle">從日常生活的小選擇，找到最值得先改善的健康習慣。</div><p class="lead">不是考試，也不是診斷。用幾分鐘看看生活裡有哪些小地方，值得先照顧一下。</p><div class="stack"><button class="btn primary" data-act="start">開始我的健康模擬</button>${resume?'<button class="btn secondary" data-act="resume">繼續上次模擬</button>':''}<button class="btn secondary" data-act="topics">自由探索健康主題</button></div></section><section class="five">${Object.values(D.categories).map(c=>`<div class="pill"><div>${c.emoji}</div><small>${c.short}</small></div>`).join('')}</section>`)}
function intakePage(){session=session||{mode:'personal',intakeIndex:0,intakeAnswers:{},answers:{},index:0,questionIds:[],selectedTasks:[]};const i=session.intakeIndex,q=intake[i];app.innerHTML=shell(`<div class="kicker">快速生活設定　${i+1} / 8</div><div class="progress"><i style="width:${(i+1)/8*100}%"></i></div><section class="card" style="margin-top:18px"><h2 class="question">${q[0]}</h2><div class="options">${q[1].map((x,j)=>`<button class="option" data-intake="${j}"><b>${'ABCDE'[j]}.</b> ${x}</button>`).join('')}</div></section>`,true)}
function weightedSelection(a){const boost={nutrition_metabolism:1,activity_muscle:1,chronic_prevention:1,sleep_stress:1,digital_ergonomics:1};if(a.eatingOut<2||a.sugar<2)boost.nutrition_metabolism+=3;if(a.sitting<2||a.exercise<2)boost.activity_muscle+=3;if(a.sleep<2)boost.sleep_stress+=3;if(a.digital<2)boost.digital_ergonomics+=3;if(a.age>0)boost.chronic_prevention+=2;const goal=['nutrition_metabolism','activity_muscle','chronic_prevention','sleep_stress','digital_ergonomics'][a.goal];boost[goal]+=4;const pools={};Object.keys(D.categories).forEach(c=>pools[c]=shuffle(bank.filter(q=>q.category===c)));const selected=[];Object.keys(pools).forEach(c=>selected.push(pools[c].pop()));while(selected.length<10){const avail=Object.keys(pools).filter(c=>pools[c].length);const bag=avail.flatMap(c=>Array(boost[c]).fill(c));selected.push(pools[bag[Math.floor(Math.random()*bag.length)]].pop())}return shuffle(selected).map(q=>q.id)}
function quizPage(){const q=bank.find(x=>x.id===session.questionIds[session.index]);if(!q){route='result';return render()}const ans=session.answers[q.id];app.innerHTML=shell(`<div class="kicker">${esc(q.categoryName)}　${session.index+1} / ${session.questionIds.length}</div><div class="progress"><i style="width:${(session.index+1)/session.questionIds.length*100}%"></i></div><section class="card" style="margin-top:18px"><span class="badge">題目 ${q.id}</span><h2 class="question">${esc(q.question)}</h2><div class="options">${q.options.map((o,j)=>`<button class="option ${ans?.optionId===o.id?'selected':''}" data-choice="${j}" ${ans?'disabled':''}>${esc(o.text)}</button>`).join('')}</div>${ans?feedback(q,ans):''}</section>`,true)}
function feedback(q,a){if(a.notApplicable)return`<div class="feedback card positive"><b>本題不適用，已排除計算 ↪️</b><p class="small">${session.mode==='personal'?'系統會自動補抽一題，確保結果仍以有效作答為依據。':'自由探索模式會直接略過本題，不納入結果。'}</p><button class="btn primary" data-act="next">下一題</button></div>`;if(a.score===2){const o=q.options.find(x=>x.id===a.optionId)||{};return`<div class="feedback"><div class="card alert"><b>⚠️ 健康提醒</b><p>${esc(o.healthAlert||q.healthAlert)}</p></div><div class="card mission"><b>🎯 小小健康任務</b><p>${esc(o.mission||q.mission)}</p></div><div class="stack"><button class="btn secondary" data-act="add-task">${session.selectedTasks.includes(q.id)?'✓ 已加入我的健康任務':'加入我的健康任務'}</button><button class="btn primary" data-act="next">${session.index===session.questionIds.length-1?'查看結果':'下一題'}</button></div></div>`}return`<div class="feedback card positive"><b>${a.score===1?'這項習慣仍有調整空間 🌱':'這個習慣目前相對不錯 👍'}</b><p class="small">持續留意自己的生活感受即可，不代表完全沒有健康風險。</p><button class="btn primary" data-act="next">${session.index===session.questionIds.length-1?'查看結果':'下一題'}</button></div>`}
function resultPage(){const scores={};Object.keys(D.categories).forEach(c=>scores[c]=0);Object.entries(session.answers||{}).forEach(([id,a])=>{const q=bank.find(x=>x.id===id);if(q&&!a.notApplicable&&Number.isFinite(a.score))scores[q.category]+=a.score});const ranks=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3);const high=Object.entries(session.answers||{}).filter(([,a])=>!a.notApplicable&&a.score===2).map(([id])=>bank.find(q=>q.id===id)).filter(Boolean);let taskIds=[...(session.selectedTasks||[]),...high.map(q=>q.id)];taskIds=[...new Set(taskIds)].slice(0,3);const tasks=get(K.tasks,[]);taskIds.forEach(id=>{const q=bank.find(x=>x.id===id),a=session.answers?.[id],o=q?.options.find(x=>x.id===a?.optionId);if(q&&!tasks.some(t=>t.questionId===id))tasks.push({questionId:id,category:q.category,mission:o?.mission||q.mission,createdAt:new Date().toISOString(),status:'pending'})});set(K.tasks,tasks);app.innerHTML=shell(`<section class="hero"><div class="eyebrow">生活習慣回顧</div><h1 style="font-size:36px">目前最值得優先照顧的健康面向</h1><p>這不是診斷或健康分數，只是依這次選擇整理的行動順序。</p></section><section class="rank" style="margin-top:18px">${ranks.map(([c,v],i)=>`<div class="card"><b>${i+1}. ${D.categories[c].emoji} ${D.categories[c].short}</b><div class="bar" style="margin-top:10px"><i style="width:${Math.min(100,35+v*8)}%"></i></div><small>${v?'較需要注意':'可以持續維持'}</small></div>`).join('')}</section><h2>我的本週健康任務</h2><section class="topics">${tasks.filter(t=>taskIds.includes(t.questionId)).slice(0,3).map(t=>`<label class="card task"><input type="checkbox" data-task="${t.questionId}" ${t.status==='completed'?'checked':''}><span>${esc(t.mission)}</span></label>`).join('')||'<div class="card">這次沒有需要優先加入的任務，繼續維持並定期檢視即可。</div>'}</section><div class="stack"><button class="btn primary" data-act="restart">重新開始</button><button class="btn secondary" data-act="home">回首頁</button></div>`,true)}
function topicsPage(){app.innerHTML=shell(`<h1>自由探索健康主題</h1><p>選一個生活面向，再決定隨機挑戰 5 題或完整探索 20 題。</p><section class="topics">${Object.entries(D.categories).map(([k,c])=>`<div class="card topic"><div class="emoji">${c.emoji}</div><div style="flex:1"><b>${c.name}</b><div class="row" style="margin-top:10px"><button class="btn secondary" data-explore="${k}:5">隨機挑戰 5 題</button><button class="btn secondary" data-explore="${k}:20">完整探索</button></div></div></div>`).join('')}</section>`,true)}
function explorePage(){quizPage()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function start(){session={mode:'personal',intakeIndex:0,intakeAnswers:{},answers:{},index:0,questionIds:[],selectedTasks:[]};set(K.session,session);route='intake';render()}
function save(){set(K.session,session)}
function bind(){document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act));document.querySelectorAll('[data-intake]').forEach(b=>b.onclick=()=>{const q=intake[session.intakeIndex];session.intakeAnswers[q[2]]=+b.dataset.intake;session.intakeIndex++;if(session.intakeIndex>=8){session.questionIds=weightedSelection(session.intakeAnswers);route='quiz'}save();render()});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const q=bank.find(x=>x.id===session.questionIds[session.index]),o=q.options[+b.dataset.choice];session.answers[q.id]={optionId:o.id,score:o.notApplicable?null:o.riskScore,notApplicable:!!o.notApplicable};save();render()});document.querySelectorAll('[data-explore]').forEach(b=>b.onclick=()=>{const [c,n]=b.dataset.explore.split(':');session={mode:'explore',answers:{},selectedTasks:[],index:0,questionIds:shuffle(bank.filter(q=>q.category===c)).slice(0,+n).map(q=>q.id)};save();route='quiz';render()});document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{const ts=get(K.tasks,[]),t=ts.find(v=>v.questionId===x.dataset.task);if(t)t.status=x.checked?'completed':'pending';set(K.tasks,ts);toast(x.checked?'任務完成，做得很踏實！':'已改回尚未完成')})}
function addReplacement(){if(session.mode!=='personal')return;const id=session.questionIds[session.index],a=session.answers[id];if(!a?.notApplicable)return;const current=bank.find(q=>q.id===id),used=new Set(session.questionIds);let choices=bank.filter(q=>q.category===current?.category&&!used.has(q.id));if(!choices.length)choices=bank.filter(q=>!used.has(q.id));if(choices.length)session.questionIds.push(shuffle(choices)[0].id)}
function act(a){if(a==='start'||a==='restart')return start();if(a==='resume'){route=session.intakeIndex<8?'intake':'quiz';return render()}if(a==='home'){route='home';return render()}if(a==='topics'){route='topics';return render()}if(a==='next'){addReplacement();session.index++;save();route=session.index>=session.questionIds.length?'result':'quiz';return render()}if(a==='add-task'){const id=session.questionIds[session.index];if(!session.selectedTasks.includes(id))session.selectedTasks.push(id);save();toast('已加入本週健康任務');return render()}if(a==='admin')return openAdmin()}
function openAdmin(){const dlg=$('#adminDialog');dlg.innerHTML=`<div class="modal"><h2>管理員模式</h2><div class="field"><label>密碼</label><input id="adminPass" type="password" autocomplete="current-password"></div><div class="row"><button class="btn primary" id="adminLogin">進入</button><button class="btn secondary" id="adminClose">取消</button></div></div>`;dlg.showModal();$('#adminClose').onclick=()=>dlg.close();$('#adminLogin').onclick=()=>{if($('#adminPass').value===(localStorage.getItem(K.adminPass)||'HSS-2026'))adminPanel(dlg);else toast('密碼不正確')}}
function adminPanel(dlg){dlg.innerHTML=`<div class="modal"><div class="row"><h2 style="flex:1">題庫管理</h2><button class="icon-btn" id="adminClose">✕</button></div><div class="row"><input id="adminSearch" placeholder="搜尋題號或關鍵字"><select id="adminCat"><option value="">全部分類</option>${Object.entries(D.categories).map(([k,c])=>`<option value="${k}">${c.short}</option>`).join('')}<option value="review">需年度複核</option></select></div><div class="admin-list" id="adminList"></div><div class="stack"><div class="row"><button class="btn secondary" id="exportBtn">匯出題庫 JSON</button><label class="btn secondary">匯入題庫 JSON<input id="importFile" type="file" accept="application/json" hidden></label></div><button class="btn danger" id="resetBank">重設回內建正式題庫</button></div></div>`;$('#adminClose').onclick=()=>dlg.close();const list=()=>{const s=$('#adminSearch').value.trim().toLowerCase(),c=$('#adminCat').value;$('#adminList').innerHTML=bank.filter(q=>(!s||(q.id+q.question).toLowerCase().includes(s))&&(!c||(c==='review'?q.needsAnnualReview:q.category===c))).map(q=>`<div class="admin-q"><button data-edit="${q.id}"><b>${q.id}</b> ${esc(q.question)} ${q.needsAnnualReview?'<span class="badge">年度複核</span>':''}</button></div>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editQuestion(dlg,b.dataset.edit))};$('#adminSearch').oninput=list;$('#adminCat').onchange=list;list();$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(bank,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='health-question-bank-v2.json';a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const x=JSON.parse(r.result);const ok=Array.isArray(x)&&x.length===100&&x.every(q=>q.id&&q.question&&Array.isArray(q.options)&&q.options.length>=3&&q.options.length<=4&&q.healthAlert&&q.mission);if(!ok)throw Error('題庫必須正好 100 題，且每題含 id、question、3 至 4 個 options、healthAlert、mission');bank=x;set(K.bank,bank);toast('題庫匯入完成');adminPanel(dlg)}catch(err){alert('匯入失敗：'+err.message)}};r.readAsText(f)};$('#resetBank').onclick=()=>{if(confirm('確定清除管理員修改，恢復內建 100 題？')){bank=structuredClone(D.questions);localStorage.removeItem(K.bank);toast('已恢復內建題庫');adminPanel(dlg)}}}
function editQuestion(dlg,id){const q=bank.find(x=>x.id===id);dlg.innerHTML=`<form class="modal" id="editForm"><div class="row"><h2 style="flex:1">編輯題目 ${q.id}</h2><button type="button" class="icon-btn" id="backAdmin">←</button></div><div class="field"><label>題目</label><textarea name="question">${esc(q.question)}</textarea></div>${q.options.map((o,i)=>`<div class="field"><label>選項 ${o.id}</label><textarea name="o${i}">${esc(o.text)}</textarea></div>`).join('')}<div class="field"><label>健康提醒</label><textarea name="alert">${esc(q.healthAlert)}</textarea></div><div class="field"><label>小小健康任務</label><textarea name="mission">${esc(q.mission)}</textarea></div><div class="field"><label>tags（逗號分隔）</label><input name="tags" value="${esc(q.tags.join(','))}"></div><div class="field"><label>imageKey</label><input name="imageKey" value="${esc(q.imageKey)}"></div><label><input type="checkbox" name="review" ${q.needsAnnualReview?'checked':''}> 需年度複核</label><button class="btn primary" style="margin-top:16px">儲存修改</button></form>`;$('#backAdmin').onclick=()=>adminPanel(dlg);$('#editForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);q.question=f.get('question').trim();q.options.forEach((o,i)=>o.text=f.get('o'+i).trim());q.healthAlert=f.get('alert').trim();q.mission=f.get('mission').trim();q.tags=f.get('tags').split(',').map(x=>x.trim()).filter(Boolean);q.imageKey=f.get('imageKey').trim();q.needsAnnualReview=f.get('review')==='on';set(K.bank,bank);toast('已儲存於這台裝置');adminPanel(dlg)}}
window.addEventListener('popstate',()=>{route='home';render()});render();
